In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
cd /content/drive/My Drive/psat_summer

/content/drive/My Drive/psat_summer


In [9]:
import pandas as pd
import numpy as np
import os

from sklearn import svm

from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, classification_report
from sklearn.ensemble import AdaBoostClassifier

from imblearn.over_sampling import SMOTE

import pickle
import joblib

In [5]:
train = pd.read_csv("train_pca.csv")

In [13]:
y = train['target']
X = train.drop('target', axis = 1)

시도 1

In [14]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state = 2021)

In [15]:
smote = SMOTE(random_state = 2021)
smote = smote.fit_sample(X_train, y_train)
smote_x = pd.DataFrame(smote[0])
smote_y = smote[1]
smote_x.columns = X_valid.columns

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [17]:
model = AdaBoostClassifier(n_estimators=1000, learning_rate=0.01, random_state=2021)
model.fit(smote_x, smote_y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.01,
                   n_estimators=1000, random_state=2021)

In [18]:
y_pred = model.predict(valid_x)

In [21]:
len(y_pred)

5600

In [22]:
valid_y

1        1
5        0
6        0
15       0
22       1
        ..
27973    0
27985    1
27986    0
27992    0
27997    0
Name: target, Length: 5600, dtype: int64

In [23]:
confusion_matrix(valid_y, y_pred)

array([[3922, 1119],
       [ 136,  423]])

In [24]:
f1_score(valid_y, y_pred)

0.40266539742979535

In [25]:
print(classification_report(valid_y, y_pred, target_names=['class 0', 'class 1']))

              precision    recall  f1-score   support

     class 0       0.97      0.78      0.86      5041
     class 1       0.27      0.76      0.40       559

    accuracy                           0.78      5600
   macro avg       0.62      0.77      0.63      5600
weighted avg       0.90      0.78      0.82      5600



시도 2

In [27]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state = 2021)

In [28]:
smote = SMOTE(random_state = 2021)
smote = smote.fit_sample(X_train, y_train)
smote_x = pd.DataFrame(smote[0])
smote_y = smote[1]
smote_x.columns = X_valid.columns

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [29]:
model = AdaBoostClassifier(n_estimators=1000, learning_rate=0.001, random_state=2021)
model.fit(smote_x, smote_y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
                   learning_rate=0.001, n_estimators=1000, random_state=2021)

In [30]:
y_pred = model.predict(valid_x)

In [31]:
len(y_pred)

5600

In [32]:
valid_y

1        1
5        0
6        0
15       0
22       1
        ..
27973    0
27985    1
27986    0
27992    0
27997    0
Name: target, Length: 5600, dtype: int64

In [33]:
confusion_matrix(valid_y, y_pred)

array([[3892, 1149],
       [ 134,  425]])

In [34]:
f1_score(valid_y, y_pred)

0.3984997655883732

In [35]:
print(classification_report(valid_y, y_pred, target_names=['class 0', 'class 1']))

              precision    recall  f1-score   support

     class 0       0.97      0.77      0.86      5041
     class 1       0.27      0.76      0.40       559

    accuracy                           0.77      5600
   macro avg       0.62      0.77      0.63      5600
weighted avg       0.90      0.77      0.81      5600



시도 3

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state = 2021)

In [ ]:
smote = SMOTE(random_state = 2021)
smote = smote.fit_sample(X_train, y_train)
smote_x = pd.DataFrame(smote[0])
smote_y = smote[1]
smote_x.columns = X_valid.columns

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [36]:
model = AdaBoostClassifier(n_estimators=3000, learning_rate=0.01, random_state=2021)
model.fit(smote_x, smote_y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.01,
                   n_estimators=3000, random_state=2021)

In [37]:
y_pred = model.predict(valid_x)

In [38]:
len(y_pred)

5600

In [39]:
valid_y

1        1
5        0
6        0
15       0
22       1
        ..
27973    0
27985    1
27986    0
27992    0
27997    0
Name: target, Length: 5600, dtype: int64

In [40]:
confusion_matrix(valid_y, y_pred)

array([[4105,  936],
       [ 171,  388]])

In [41]:
f1_score(valid_y, y_pred)

0.4121083377588954

In [42]:
print(classification_report(valid_y, y_pred, target_names=['class 0', 'class 1']))

              precision    recall  f1-score   support

     class 0       0.96      0.81      0.88      5041
     class 1       0.29      0.69      0.41       559

    accuracy                           0.80      5600
   macro avg       0.63      0.75      0.65      5600
weighted avg       0.89      0.80      0.83      5600



시도 4

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state = 2021)

In [ ]:
smote = SMOTE(random_state = 2021)
smote = smote.fit_sample(X_train, y_train)
smote_x = pd.DataFrame(smote[0])
smote_y = smote[1]
smote_x.columns = X_valid.columns

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [43]:
model = AdaBoostClassifier(n_estimators=10000, learning_rate=0.01, random_state=2021)
model.fit(smote_x, smote_y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.01,
                   n_estimators=10000, random_state=2021)

In [44]:
y_pred = model.predict(valid_x)

In [45]:
len(y_pred)

5600

In [46]:
valid_y

1        1
5        0
6        0
15       0
22       1
        ..
27973    0
27985    1
27986    0
27992    0
27997    0
Name: target, Length: 5600, dtype: int64

In [47]:
confusion_matrix(valid_y, y_pred)

array([[4293,  748],
       [ 225,  334]])

In [48]:
f1_score(valid_y, y_pred)

0.40706886045094454

In [49]:
print(classification_report(valid_y, y_pred, target_names=['class 0', 'class 1']))

              precision    recall  f1-score   support

     class 0       0.95      0.85      0.90      5041
     class 1       0.31      0.60      0.41       559

    accuracy                           0.83      5600
   macro avg       0.63      0.72      0.65      5600
weighted avg       0.89      0.83      0.85      5600



n_estimators=3000, learning_rate=0.01, random_state=2021

In [ ]:
# train set에 대한 smote 시행