In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [4]:
cd /content/drive/My Drive/psat_summer

/content/drive/My Drive/psat_summer


In [2]:
import pandas as pd
import numpy as np
import os

from sklearn import svm

from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, classification_report
from sklearn.ensemble import AdaBoostClassifier

from imblearn.over_sampling import SMOTE

import pickle
import joblib

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [5]:
train = pd.read_csv("train_pca.csv")

In [6]:
y = train['target']
X = train.drop('target', axis = 1)

시도 1

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state = 2021)

In [ ]:
smote = SMOTE(random_state = 2021)
smote = smote.fit_sample(X_train, y_train)
smote_x = pd.DataFrame(smote[0])
smote_y = smote[1]
smote_x.columns = X_valid.columns

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
model = AdaBoostClassifier(n_estimators=1000, learning_rate=0.01, random_state=2021)
model.fit(smote_x, smote_y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.01,
                   n_estimators=1000, random_state=2021)

In [ ]:
y_pred = model.predict(valid_x)

In [ ]:
len(y_pred)

5600

In [ ]:
valid_y

1        1
5        0
6        0
15       0
22       1
        ..
27973    0
27985    1
27986    0
27992    0
27997    0
Name: target, Length: 5600, dtype: int64

In [ ]:
confusion_matrix(valid_y, y_pred)

array([[3922, 1119],
       [ 136,  423]])

In [ ]:
f1_score(valid_y, y_pred)

0.40266539742979535

In [ ]:
print(classification_report(valid_y, y_pred, target_names=['class 0', 'class 1']))

              precision    recall  f1-score   support

     class 0       0.97      0.78      0.86      5041
     class 1       0.27      0.76      0.40       559

    accuracy                           0.78      5600
   macro avg       0.62      0.77      0.63      5600
weighted avg       0.90      0.78      0.82      5600



시도 2

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state = 2021)

In [ ]:
smote = SMOTE(random_state = 2021)
smote = smote.fit_sample(X_train, y_train)
smote_x = pd.DataFrame(smote[0])
smote_y = smote[1]
smote_x.columns = X_valid.columns

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
model = AdaBoostClassifier(n_estimators=1000, learning_rate=0.001, random_state=2021)
model.fit(smote_x, smote_y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
                   learning_rate=0.001, n_estimators=1000, random_state=2021)

In [ ]:
y_pred = model.predict(valid_x)

In [ ]:
len(y_pred)

5600

In [ ]:
valid_y

1        1
5        0
6        0
15       0
22       1
        ..
27973    0
27985    1
27986    0
27992    0
27997    0
Name: target, Length: 5600, dtype: int64

In [ ]:
confusion_matrix(valid_y, y_pred)

array([[3892, 1149],
       [ 134,  425]])

In [ ]:
f1_score(valid_y, y_pred)

0.3984997655883732

In [ ]:
print(classification_report(valid_y, y_pred, target_names=['class 0', 'class 1']))

              precision    recall  f1-score   support

     class 0       0.97      0.77      0.86      5041
     class 1       0.27      0.76      0.40       559

    accuracy                           0.77      5600
   macro avg       0.62      0.77      0.63      5600
weighted avg       0.90      0.77      0.81      5600



시도 3

In [ ]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state = 2021)

In [ ]:
smote = SMOTE(random_state = 2021)
smote = smote.fit_sample(X_train, y_train)
smote_x = pd.DataFrame(smote[0])
smote_y = smote[1]
smote_x.columns = X_valid.columns

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
model = AdaBoostClassifier(n_estimators=3000, learning_rate=0.01, random_state=2021)
model.fit(smote_x, smote_y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.01,
                   n_estimators=3000, random_state=2021)

In [ ]:
y_pred = model.predict(X_valid)

In [ ]:
len(y_pred)

8400

In [ ]:
confusion_matrix(y_valid, y_pred)

array([[6171, 1410],
       [ 251,  568]])

In [ ]:
f1_score(y_valid, y_pred)

0.406149445834823

In [ ]:
print(classification_report(y_valid, y_pred, target_names=['class 0', 'class 1']))

              precision    recall  f1-score   support

     class 0       0.96      0.81      0.88      7581
     class 1       0.29      0.69      0.41       819

    accuracy                           0.80      8400
   macro avg       0.62      0.75      0.64      8400
weighted avg       0.90      0.80      0.84      8400



In [ ]:
test = pd.read_csv("test_pca.csv")

In [ ]:
test.shape

(2000, 189)

In [ ]:
prediction = model.predict(test) # has only x variables

In [ ]:
submission = pd.DataFrame(columns = ['id', 'target'])
submission['id'] = range(1,2001)

In [ ]:
submission['target'] = prediction

In [ ]:
submission['target'].value_counts()

0    1511
1     489
Name: target, dtype: int64

In [ ]:
submission.to_csv("adaboost_ver1.csv", header = True, index = False)

In [ ]:
submission

id  target
0        1       0
1        2       0
2        3       0
3        4       0
4        5       0
...    ...     ...
1995  1996       0
1996  1997       0
1997  1998       0
1998  1999       0
1999  2000       0

[2000 rows x 2 columns]

시도 4

In [51]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state = 2021)

In [52]:
smote = SMOTE(random_state = 2021)
smote = smote.fit_sample(X_train, y_train)
smote_x = pd.DataFrame(smote[0])
smote_y = smote[1]
smote_x.columns = X_valid.columns

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [53]:
model = AdaBoostClassifier(n_estimators=600, learning_rate=0.05, random_state=2021)
model.fit(smote_x, smote_y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.05,
                   n_estimators=600, random_state=2021)

In [54]:
joblib.dump(model, 'AD.pkl')

['AD.pkl']

In [55]:
y_pred = model.predict(X_valid)

In [56]:
len(y_pred)

8400

In [57]:
confusion_matrix(y_valid, y_pred)

array([[6170, 1411],
       [ 251,  568]])

In [58]:
f1_score(y_valid, y_pred)

0.40600428877769834

In [59]:
print(classification_report(y_valid, y_pred, target_names=['class 0', 'class 1']))

              precision    recall  f1-score   support

     class 0       0.96      0.81      0.88      7581
     class 1       0.29      0.69      0.41       819

    accuracy                           0.80      8400
   macro avg       0.62      0.75      0.64      8400
weighted avg       0.90      0.80      0.83      8400



In [60]:
test = pd.read_csv("test_pca.csv")

In [61]:
test.shape

(2000, 189)

In [62]:
prediction = model.predict(test) # has only x variables

In [63]:
submission = pd.DataFrame(columns = ['id', 'target'])
submission['id'] = range(1,2001)

In [64]:
submission['target'] = prediction

In [65]:
submission['target'].value_counts()

0    1509
1     491
Name: target, dtype: int64

In [66]:
submission.to_csv("adaboost_ver4.csv", header = True, index = False)

시도 5

In [33]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state = 2021)

In [34]:
smote = SMOTE(random_state = 2021)
smote = smote.fit_sample(X_train, y_train)
smote_x = pd.DataFrame(smote[0])
smote_y = smote[1]
smote_x.columns = X_valid.columns

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [35]:
model = AdaBoostClassifier(n_estimators=1000, learning_rate=0.05, random_state=2021)
model.fit(smote_x, smote_y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.05,
                   n_estimators=1000, random_state=2021)

In [36]:
joblib.dump(model, 'AD.pkl')

['AD.pkl']

In [37]:
y_pred = model.predict(X_valid)

In [38]:
len(y_pred)

8400

In [39]:
confusion_matrix(y_valid, y_pred)

array([[6311, 1270],
       [ 276,  543]])

In [40]:
f1_score(y_valid, y_pred)

0.4126139817629179

In [41]:
print(classification_report(y_valid, y_pred, target_names=['class 0', 'class 1']))

              precision    recall  f1-score   support

     class 0       0.96      0.83      0.89      7581
     class 1       0.30      0.66      0.41       819

    accuracy                           0.82      8400
   macro avg       0.63      0.75      0.65      8400
weighted avg       0.89      0.82      0.84      8400



In [42]:
test = pd.read_csv("test_pca.csv")

In [43]:
test.shape

(2000, 189)

In [44]:
prediction = model.predict(test) # has only x variables

In [45]:
submission = pd.DataFrame(columns = ['id', 'target'])
submission['id'] = range(1,2001)

In [46]:
submission['target'] = prediction

In [47]:
submission['target'].value_counts()

0    1546
1     454
Name: target, dtype: int64

In [50]:
submission.to_csv("adaboost_ver5.csv", header = True, index = False)